### ISSUE TITLE
!sprint for x at y schedules incorrect times

### ISSUE THREAD

**Issue by moritzuehling** [cwarwicker/discord-WriterBot#31]
The code I tested seems to work locally - however, when using your deployed instance it doesn't seem to work?

![image](https://user-images.githubusercontent.com/7847742/61984076-298ce200-b003-11e9-9ef3-54ad4ab7b930.png)

When I test some of the relevant code in my local console, then it seems to work, so it looks like the API is being used incorrectly, or I'm overlooking something. 

![image](https://user-images.githubusercontent.com/7847742/61984120-5214dc00-b003-11e9-9cad-113cdcdf0d8e.png)

**Comment by moritzuehling** [comment]
By the way, feel free to add me on discord: moritz#0001

**Comment by cwarwicker** [comment]
I haven't pushed it up to the live site yet. 
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 26/07/2019, 23:13 Moritz <notifications@github.com> wrote:
The code I tested seems to work locally - however, when using your deployed instance it doesn't seem to work?

When I test some of the relevant code in my local console, then it seems to work, so it looks like the API is being used incorrectly, or I'm overlooking something.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cwarwicker/discord-WriterBot/issues/31?email_source=notifications\u0026email_token=AASVDGFGJIZLXYULXTAR6JTQBNZHZA5CNFSM4IHHQ2YKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBZ3VVA",
"url": "https://github.com/cwarwicker/discord-WriterBot/issues/31?email_source=notifications\u0026email_token=AASVDGFGJIZLXYULXTAR6JTQBNZHZA5CNFSM4IHHQ2YKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBZ3VVA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by moritzuehling** [comment]
That explains it!

**Comment by cwarwicker** [comment]
I've pushed it up now.
